---
custom_ami_operation: create
source_ami_filters:
  architecture: x86_64
  virtualization-type: hvm
  root-device-type: ebs
  name: Fedora-Cloud-Base-35-*
source_ami_user_name: ec2-user

custom_ami_ec2_instance_type: t2.large

custom_ami_recreate_if_exists: false
