---
- name: Run create_tgw_attach_vpc role
  block:
    - name: Create  transit gateway
      amazon.aws.ec2_transit_gateway:
        state: present
        description: "{{ manage_transit_gateway_transit_gateway.description }}"
        asn: "{{ manage_transit_gateway_transit_gateway.asn }}"
        tags: "{{ manage_transit_gateway_transit_gateway.tags }}"
      register: manage_transit_gateway_tgw_result

    - name: Verify that transit gateway has been created/updated
      ansible.builtin.debug:
        msg: Transit Gateway successfully created/updated.
      when: manage_transit_gateway_tgw_result.changed

    - name: Print debug msg
      ansible.builtin.debug:
        msg: Transit Gateway '{{ manage_transit_gateway_tgw_result.transit_gateway.transit_gateway_id }}' exists, no updates needed.
      when: not manage_transit_gateway_tgw_result.changed

    - name: Create VPC attachment
      when: vars["manage_transit_gateway_vpc_attachment"] is defined
      ansible.builtin.include_tasks: create_vpc_attachment.yaml
      loop: "{{ manage_transit_gateway_vpc_attachment }}"

    - name: Create VPN attachment
      when: vars["manage_transit_gateway_vpn_attachment"] is defined
      ansible.builtin.include_tasks: create_vpn_attachment.yaml
      loop: "{{ manage_transit_gateway_vpn_attachment }}"

    - name: Create route table entries
      when: vars["manage_transit_gateway_vpc_route_table"] is defined
      ansible.builtin.include_tasks: add_vpc_route_entries.yaml
      loop: "{{ manage_transit_gateway_vpc_route_table }}"
