---
- name: Fail when required parameters are not provided
  ansible.builtin.fail:
    msg: Please provide required parameters to delete VPC peering (refer documentation for more information)
  when: manage_vpc_peering_region is not defined or manage_vpc_peering_vpc_peering_conn_id is not defined

- name: Delete vpc peering connection request
  block:
    - name: Delete a local VPC peering connection
      amazon.aws.ec2_vpc_peering:
        region: "{{ manage_vpc_peering_region }}"
        peering_id: "{{ manage_vpc_peering_vpc_peering_conn_id }}"
        state: absent
      register: manage_vpc_peering_vpc_peer

    - name: Wait for VPC peering connection to be deleted
      ansible.builtin.pause:
        seconds: 5
