---
- name: Run ec2_networking_resources role
  module_defaults:
    group/aws: "{{ aws_setup_credentials__output }}"
  block:
    - name: Include create operations
      ansible.builtin.include_tasks: create.yml
      when: ec2_networking_resources_operation == 'create'

    - name: Include delete operations
      ansible.builtin.include_tasks: delete.yml
      when: ec2_networking_resources_operation == 'delete'
