---
- name: List existing AMI by name
  amazon.aws.ec2_ami_info:
    filters:
      name: "{{ custom_ami_name }}"
  register: customized_ami__existing_amis

- name: Delete existing images
  amazon.aws.ec2_ami:
    name: "{{ item.name }}"
    image_id: "{{ item.image_id }}"
    wait: true
    state: absent
  with_items: "{{ customized_ami__existing_amis.images }}"
  when: custom_ami_recreate_if_exists | bool

- name: List existing AMI by name
  amazon.aws.ec2_ami_info:
    filters:
      name: "{{ custom_ami_name }}"
  register: customized_ami__existing_amis

- name: Create custom AMI
  when: customized_ami__existing_amis.images | length == 0
  block:
    - name: Get Source AMI identifier
      ansible.builtin.include_tasks: read_source_ami.yaml

    - name: Get Source AMI identifier
      ansible.builtin.include_tasks: create_ec2_resources.yaml

    - name: Create custom AMI
      ansible.builtin.include_tasks: create_ami.yaml

  always:
    - name: Include 'tasks/delete_ec2_resources.yaml' file
      ansible.builtin.include_tasks: tasks/delete_ec2_resources.yaml

- name: Check that existing AMI found
  ansible.builtin.debug:
    msg: "Existing AMI found with name: '{{ custom_ami_name }}'"
  when:
    - customized_ami__existing_amis.images | length > 0
