---
name: Linters
'on':
  push:
    branches:
      - main
  pull_request:

jobs:

  ansible-lint:
    uses: abikouo/github_actions/.github/workflows/ansible-lint.yml@ansible_lint_versionning
    with:
      action_ref: v6.15.0
