---
name: Linters
'on':
  push:
    branches:
      - main
  pull_request:

jobs:

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6.16.0
